[platformio]
default_envs = xiao_esp32s3_sense

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:xiao_esp32s3_sense]
; 캣센서: XIAO ESP32S3 Sense + OV3660
board = seeed_xiao_esp32s3
build_src_filter = +<camera_node/**> -<display_node/**>
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:xiao_camera_probe]
board = seeed_xiao_esp32s3
build_src_filter = +<camera_probe/**> -<camera_node/**> -<display_node/**>
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:display_esp32s3]
; 캣모니터: ESP32-S3 WROOM-1 + TFT + buttons
board = esp32-s3-devkitc-1
build_src_filter = +<display_node/**> -<camera_node/**>
lib_deps =
  adafruit/Adafruit GFX Library @ ^1.12.0
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
  bodmer/TJpg_Decoder @ ^1.1.0
